# albert = User.create(username: "albert83", email: "albert83@gmail.com", password: "cat47")
# tommy = User.create(username: "tommy459", email: "tommy459@gmail.com", password: "blue9")
# sam = User.create(username: "sam2", email: "sam2@gmail.com", password: "hippo8")
# rascal = User.create(username: "rascal215", email: "rascal215@gmail.com", password: "horse7")

# albert_writer = Writer.create(user_id: albert.id)
# tommy_writer = Writer.create(user_id: tommy.id)
# sam_writer = Writer.create(user_id: sam.id)
# rascal_writer = Writer.create(user_id: rascal.id)

# albert_director = Director.create(user_id: albert.id)
# tommy_director = Director.create(user_id: tommy.id)
# sam_director = Director.create(user_id: sam.id)
# rascal_director = Director.create(user_id: rascal.id)

# iron_rush = Film.create(title: "Iron Rush", genre: "action", runtime: "158", writers: [sam_writer], directors: [albert_director])
# tap_out = Film.create(title: "Tap Out", genre: "drama", runtime: "10", writers: [rascal_writer], directors: [rascal_director])
# bee_fly = Film.create(title: "Bee Fly", genre: "action", runtime: "245", writers: [tommy_writer], directors: [sam_director])
# rainbow_stars = Film.create(title: "Rainbow Stars", genre: "action", runtime: "190", writers: [sam_writer], directors: [rascal_director, sam_director])
# plum = Film.create(title: "Plum", genre: "comedy", runtime: "78", writers: [tommy_writer, sam_writer], directors: [tommy_director])
