albert = User.create(username: "albert83", email: "albert83@gmail.com", password: "cat47")
tommy = User.create(username: "tommy459", email: "tommy459@gmail.com", password: "blue9")
sam = User.create(username: "sam2", email: "sam2@gmail.com", password: "hippo8")
rascal = User.create(username: "rascal215", email: "rascal215@gmail.com", password: "horse7")

albert_writer = Writer.create(user_id: albert.id)
tommy_writer = Writer.create(user_id: tommy.id)
sam_writer = Writer.create(user_id: sam.id)
rascal_writer = Writer.create(user_id: rascal.id)

albert_director = Director.create(user_id: albert.id)
tommy_director = Director.create(user_id: tommy.id)
sam_director = Director.create(user_id: sam.id)
rascal_director = Director.create(user_id: rascal.id)

iron_rush = Film.create(title: "Iron Rush", genre: "action", runtime: "158", writer: [], director: [], user: [albert])
tap_out = Film.create(title: "Tap Out", genre: "action", runtime: "158", writer: [], director: [], user: [tommy])
bee_fly = Film.create(title: "Bee Fly", genre: "action", runtime: "158", writer: [], director: [])
rainbow_stars = Film.create(title: "Rainbow Stars", genre: "action", runtime: "158", writer: [], director: [], user: [tommy, sam])
plum = Film.create(title: "Iron Rush", genre: "action", runtime: "158", writer: [], director: [], user: [rascal])
